#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo " Generates a stand up report:"
  echo " standup"
  echo " [more info needed]"
  echo ""
  exit
}

[ "$action" = "standup" ] && {
     ruby $TODO_ACTIONS_DIR/standup.rb
}
