#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Customized standup:"
  echo "    standup"
  echo "      Generates a report of tasks completed \"Yesterday\", and tasks left to do"
  exit
}

[ "$action" = "standup" ] && {
     ruby $TODO_ACTIONS_DIR/standup.rb
}
